name: Build React Vite App

on:
  push:
    tags:
      - "release-*"
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_upload:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Ensure the token has write permissions for contents
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Package
        run: ./package.sh

      - name: Upload build artifact
        if: github.ref != 'refs/tags/release-*'
        uses: actions/upload-artifact@v4.6.1
        with:
          name: build-artifact
          path: output/mediaremote.zip

      - name: Checkout releases branch
        run: |
          git fetch origin releases
          git checkout releases
  
      - name: Copy build artifact to releases branch
        run: |
          cp output/mediaremote.zip ./mediaremote.zip
          mv output/mediaremote.zip ./mediaremote.$(date +%s).zip
  
      - name: Commit and push build artifact
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add mediaremote*.zip
          git commit -m "Add build artifact from ${GITHUB_SHA}"
          git push origin releases
